// <auto-generated />
using ECommerce_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerce_App.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20200812000937_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerce_App.Models.Flummery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Compliment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Flummery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 9,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 10,
                            Calories = 3000,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Weight = 0.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
