// <auto-generated />
using ECommerce_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ECommerce_App.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerce_App.Models.Flummery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<string>("Compliment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Flummery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 1525,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 2,
                            Calories = 1300,
                            Compliment = "That tie looks great on you! Is it new?",
                            Manufacturer = "Acme Baking",
                            Name = "Tied for First",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 3,
                            Calories = 900,
                            Compliment = "Oh wow, you really tried your hardest on that!",
                            Manufacturer = "Acme Baking",
                            Name = "Tryion",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 4,
                            Calories = 912,
                            Compliment = "That chili would be pretty spicy to an infant.",
                            Manufacturer = "Acme Baking",
                            Name = "Baby Cowboy",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 5,
                            Calories = 2100,
                            Compliment = "Stylish if your grandparents dressed you.",
                            Manufacturer = "Acme Baking",
                            Name = "Polka",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 6,
                            Calories = 1792,
                            Compliment = "What a nice sorting algorithm.",
                            Manufacturer = "Acme Baking",
                            Name = "Lark on the Wing",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 7,
                            Calories = 1135,
                            Compliment = "Yeah, that's a nice loaf of quarantine sourdough.",
                            Manufacturer = "Acme Baking",
                            Name = "Scarce Flour",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 8,
                            Calories = 1280,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 9,
                            Calories = 615,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Price = 9.99m,
                            Weight = 0.5m
                        },
                        new
                        {
                            Id = 10,
                            Calories = 1952,
                            Compliment = "I can't believe you managed to pull that off. Good job.",
                            Manufacturer = "Acme Baking",
                            Name = "Job Jelly",
                            Price = 9.99m,
                            Weight = 0.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
